// ==UserScript==
// @name         YouTube Dual Subtitles for French, German, Russian, Ukrainian
// @namespace    http://tampermonkey.net/
// @version      1.1
// @license      Unlicense
// @description  Add dual subtitles to YouTube videos
// @author       Jim Chen
// @homepage     https://jimchen.me
// @supportURL   https://github.com/jimchen2/youtube-dual-subtitles/issues
// @match        https://www.youtube.com/watch?*
// @match        https://www.youtube.com/embed/*
// @match        https://m.youtube.com/watch?*
// @match        https://m.youtube.com/embed/*
// @match        https://cdn.jimchen.me/*
// @run-at       document-idle
// @downloadURL https://update.greasyfork.org/scripts/527345/YouTube%20Dual%20Subtitles%20for%20French%2C%20German%2C%20Russian%2C%20Ukrainian.user.js
// @updateURL https://update.greasyfork.org/scripts/527345/YouTube%20Dual%20Subtitles%20for%20French%2C%20German%2C%20Russian%2C%20Ukrainian.meta.js
// ==/UserScript==

(function () {
  "use strict";

  console.log("[Dual Subs] Script initialized");

  async function handleVideoNavigation() {
    console.log("[Dual Subs] Navigation detected");
    removeSubs();
    await processSubtitles();
  }

async function processSubtitles() {
    console.log("[Dual Subs] Starting subtitle processing");

    const playerData = await new Promise((resolve) => {
        const checkForPlayer = () => {
            console.log("[Dual Subs] Trying to get Caption Data");
            const captionData = window.location.href.startsWith("https://www.youtube")
                ? document.getElementsByTagName("ytd-app")[0]?.data?.playerResponse?.captions?.playerCaptionsTracklistRenderer
                : document.getElementsByTagName("ytm-app")[0]?.data?.playerResponse?.captions?.playerCaptionsTracklistRenderer;

            if (captionData) {
                console.log("[Dual Subs] Successfully retrieved caption data");
                resolve(captionData);
            } else {
                console.log("[Dual Subs] Caption data not found, retrying in 500ms");
                setTimeout(checkForPlayer, 500);
            }
        };
        checkForPlayer(); // Initial call
    });

    if (!playerData) {
        console.log("[Dual Subs] No player data available");
        return;
    }

    const { captionTracks, translationLanguages } = playerData;

    if (!captionTracks || !translationLanguages) {
        console.log("[Dual Subs] Missing caption tracks or translation languages");
        return;
    }

    const learningTrack = findLearningTrack(captionTracks);
    if (!learningTrack) {
        console.log("[Dual Subs] No suitable learning track found");
        return;
    }

    await addSubtitles(learningTrack, translationLanguages);
}



  function findLearningTrack(captionTracks) {
      console.log("[Dual Subs] Finding auto-generated track");

    const autoGenerated = captionTracks.find((track) => ["a.ru", "a.uk", "a.de", "a.fr"].includes(track.vssId));

    if (autoGenerated) {
      console.log("[Dual Subs] Found auto-generated track", autoGenerated.vssId);
      return autoGenerated;
    }

    const manualTrack = captionTracks.find((track) => [".ru", ".uk", ".de", ".fr"].includes(track.vssId));

    console.log("[Dual Subs] Found manual track");
    return manualTrack;
  }

  async function addSubtitles(learningTrack, translationLanguages) {
      console.log(`[Dual Subs] addSubtitles called adding ${learningTrack.vssId} and English`);

    const englishLang = translationLanguages.find((lang) => lang.languageCode == "en");

    if (englishLang) {
        console.log("[Dual Subs] found English Lang");

      await addOneSubtitle(`${learningTrack.baseUrl}&fmt=vtt&tlang=${englishLang.languageCode}`, "en");
    }

        console.log("[Dual Subs] English Lang added");

    const originalLang = learningTrack.vssId.replace(/[.a]/g, "");
    await addOneSubtitle(`${learningTrack.baseUrl}&fmt=vtt`, originalLang);
  }

    async function addOneSubtitle(url, lang, maxRetries = 5, delay = 1000) {
        console.log(`[Dual Subs] Attempting to add ${lang} subtitles at url ${url}`);

        const video = document.querySelector("video");
        if (!video) {
            console.log("[Dual Subs] No video element found, waiting...");
            await new Promise(resolve => setTimeout(resolve, delay));
            if (maxRetries > 0) {
                return addOneSubtitle(url, lang, maxRetries - 1, delay);
            }
            console.error("[Dual Subs] Failed to find video element after retries");
            return;
        }

        try {
            console.log(`[Dual Subs] Fetching subtitles for ${lang}`);
            const response = await fetch(url);
            if (!response.ok) {
                throw new Error(`HTTP error! status: ${response.status}`);
            }

            const subtitleData = (await response.text()).replaceAll("align:start position:0%", "");

            const track = document.createElement("track");
            track.default = true;
            track.src = "data:text/vtt," + encodeURIComponent(subtitleData);

            // Add delay before appending to ensure video is ready
            await new Promise(resolve => setTimeout(resolve, delay));

            video.appendChild(track);
            track.track.mode = "showing";

            console.log(`[Dual Subs] Successfully added ${lang} subtitles`);
        } catch (error) {
            console.error(`[Dual Subs] Error adding ${lang} subtitles:`, error);
            if (maxRetries > 0) {
                console.log(`[Dual Subs] Retrying... (${maxRetries} attempts remaining)`);
                await new Promise(resolve => setTimeout(resolve, delay));
                return addOneSubtitle(url, lang, maxRetries - 1, delay);
            }
        }
    }


  // Wait for page load and YouTube's own scripts to initialize
  let lastUrl = location.href;
  const observer = new MutationObserver(() => {
    if (location.href !== lastUrl) {
      lastUrl = location.href;
      setTimeout(handleVideoNavigation, 1000);
    }
  });

  observer.observe(document.body, {
    childList: true,
    subtree: true,
  });

  // Initial run
  setTimeout(handleVideoNavigation, 1000);

    function removeSubs() {
        console.log("[Dual Subs] Attempting to remove subtitles");
        const video = document.getElementsByTagName("video")[0];

        if (!video) {
            console.log("[Dual Subs] No video element found");
            return;
        }

        const tracks = video.getElementsByTagName("track");
        if (tracks.length === 0) {
            return;
        }

        Array.from(tracks).forEach(function (ele) {
            ele.track.mode = "hidden";
            ele.parentNode.removeChild(ele);
        });
        console.log(`[Dual Subs] Successfully removed ${tracks.length} subtitle track(s)`);
    }

})();
