// ==UserScript==
// @name         Video Sites Enhancer
// @namespace    http://tampermonkey.net/
// @version      1.0.7
// @license      Unlicense
// @description  Add keyboard shortcuts and dual subtitles to YouTube videos
// @author       Jim Chen
// @homepage     https://jimchen.me
// @match        https://*.youtube.com/*
// @match        *://*.bilibili.com/*
// @match        *://vkvideo.ru/*
// @match        *://rutube.ru/*
// @match        *://*.1tv.ru/*
// @match        *://*.matchtv.ru/*
// @match        file://*/*
// @updateURL    https://raw.githubusercontent.com/jimchen2/userscripts/master/video-sites-enhancer.user.js
// @downloadURL  https://raw.githubusercontent.com/jimchen2/userscripts/master/video-sites-enhancer.user.js
// @run-at       document-idle
// ==/UserScript==
(function () {
  if (location.href.startsWith("https://www.youtube.com")) {
    document.addEventListener("yt-navigate-finish", () => {
      handleVideoNavigation();
    });
  } else if (location.href.startsWith("https://m.youtube.com")) {


let lastUrl = window.location.href.split('#')[0];

function checkUrlChanged() {
  const currentUrl = window.location.href.split('#')[0];
  console.log("url", window.location.href);
  console.log("last url", lastUrl);

  if (currentUrl !== lastUrl) {
    lastUrl = currentUrl;
    handleVideoNavigation();
  }
}

window.addEventListener("popstate", checkUrlChanged);

const originalPushState = history.pushState;
const originalReplaceState = history.replaceState;

history.pushState = function() {
  const result = originalPushState.apply(this, arguments);
  checkUrlChanged();
  return result;
};

history.replaceState = function() {
  const result = originalReplaceState.apply(this, arguments);
  checkUrlChanged();
  return result;
};

handleVideoNavigation();



  } else if (location.href.startsWith("https://www.youtube.com/embed")) {
    handleVideoNavigation();
  }

  async function handleVideoNavigation() {
    console.log("FIRED");
    removeSubs();
    let subtitleURL = await extractSubtitleUrl();
    if (subtitleURL == null) return;
    await addOneSubtitle(subtitleURL + "&tlang=en");
    await addOneSubtitle(subtitleURL);
  }

  async function extractSubtitleUrl() {

    function extractYouTubeVideoID() {
      const url = window.location.href;
      const patterns = {
          standard: /(?:https?:\/\/)?(?:www\.)?youtube\.com\/watch\?(?:[^?&]+&)*v=([^&]+)/,
          embed: /(?:https?:\/\/)?(?:www\.)?youtube\.com\/embed\/([^?]+)/,
        mobile: /(?:https?:\/\/)?(?:m\.)?youtube\.com\/watch\?v=([^&]+)/,
      };

      let videoID = null;
      if (patterns.standard.test(url)) {
        videoID = url.match(patterns.standard)[1];
      } else if (patterns.embed.test(url)) {
        videoID = url.match(patterns.embed)[1];
      }else if (patterns.mobile.test(url)) {
        videoID = url.match(patterns.mobile)[1];
      }
      return videoID;
    }
    let videoID = extractYouTubeVideoID();
    if (videoID == null) return;

    const playerData = await new Promise((resolve, reject) => {
      let retries = 0;
      const checkForPlayer = (maxRetries = 2, delay = 3000) => {
        console.log("CHECKED, retries", retries);
        let ytAppData = document.querySelector("#movie_player");
        let captionData = ytAppData?.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.captionTracks;

        if (captionData) {
          const fetchedBaseUrl = captionData[0].baseUrl;
          const fetchedVideoID = fetchedBaseUrl.match(/[?&]v=([^&]+)/)?.[1];
          if (fetchedVideoID !== videoID) {
            if (retries >= maxRetries) {
              reject(new Error("Max retries reached or video ID mismatch"));
            } else {
              retries++;
              setTimeout(checkForPlayer, delay);
            }
          } else {
            resolve(captionData);
          }
        } else {
          if (retries >= maxRetries) {
            reject(new Error("Max retries reached, caption data not found"));
          } else {
            retries++;
            setTimeout(checkForPlayer, delay);
          }
        }
      };
      checkForPlayer();
    });
    if (!playerData) return;
    const hasForeignTrack = playerData.some(({ vssId }) => /(ru|uk|de|es)/.test(vssId));
    if (hasForeignTrack) {
      const autoGeneratedTrack = playerData.find((track) => ["a.ru", "a.uk", "a.de", "a.es"].includes(track.vssId));
      const manualTrack = playerData.find((track) => ["ru", "uk", "de", "es"].some((code) => track.vssId.includes(code)));
      const otherTrack = autoGeneratedTrack || manualTrack;
      if (!otherTrack) return;
      return `${otherTrack.baseUrl}&fmt=vtt`;
    }
  }

  async function addOneSubtitle(url, maxRetries = 2, delay = 3000) {
    const video = document.querySelector("video");
    try {
      const response = await fetch(url);
      const subtitleData = (await response.text()).replaceAll("align:start position:0%", "");
      const track = document.createElement("track");
      track.src = "data:text/vtt," + encodeURIComponent(subtitleData);
      await new Promise((resolve) => setTimeout(resolve, delay));
      video.appendChild(track);
      track.track.mode = "showing";
    } catch (error) {
      if (maxRetries > 0) {
        await new Promise((resolve) => setTimeout(resolve, delay));
        return addOneSubtitle(url, maxRetries - 1, delay);
      }
    }
  }
  function removeSubs() {
    const video = document.getElementsByTagName("video")[0];
    if (!video) return;
    const tracks = video.getElementsByTagName("track");
    Array.from(tracks).forEach(function (ele) {
      ele.track.mode = "hidden";
      ele.parentNode.removeChild(ele);
    });
  }
  if (!location.href.startsWith("https://www.youtube.com") && !location.href.startsWith("https://m.youtube.com")) {
    document.addEventListener("keydown", function (e) {
      const activeElement = document.activeElement;
      const isInputElement = activeElement && /input|textarea/i.test(activeElement.tagName);

      // If typing in an input/textarea, only allow Escape to blur
      if (isInputElement) {
        if (e.key === "Escape") {
          activeElement.blur();
        }
        return;
      }

      const hostname = window.location.hostname;
      const isBilibili = hostname.includes("bilibili.com");
      const isVkVideo = hostname.includes("vkvideo.ru");
      const isRuTube = hostname.includes("rutube.ru");

      // --- Search Focus ---
      if (e.key === "/" || e.key === ".") {
        let searchInput = null;

        if (isBilibili) {
          const selector = window.location.href.startsWith("https://search.bilibili.com/")
            ? 'input.search-input-el[placeholder="输入关键字搜索"]' // More specific selector for search page
            : ".nav-search-input"; // General header search
          searchInput = document.querySelector(selector);
        } else if (isVkVideo) {
          // VK Video specific selector
          searchInput = document.querySelector("#video_service_search_input");
        } else if (isRuTube) {
          // RuTube specific selector for search input
          searchInput = document.querySelector(".wdp-search-line-module__input");
        }

        if (searchInput) {
          e.preventDefault(); // Prevent browser's default find action
          searchInput.focus();
          searchInput.select(); // Select existing text
        }
        return;
      }

      const video = document.querySelector("video");
      if (!video) return;

      // Number keys 0-9 for seeking
      if (/^[0-9]$/.test(e.key)) {
        e.preventDefault();
        const percentage = parseInt(e.key) * 10;
        if (video.duration && isFinite(video.duration)) {
          video.currentTime = (percentage / 100) * video.duration;
        }
        return;
      }

      let keyHandled = false;

      if (e.shiftKey && (e.key === ">" || e.key === "Ю")) {
        // Increase speed
        video.playbackRate = Math.min(video.playbackRate + 0.25, 4); // Capped at 4x
        keyHandled = true;
      } else if (e.shiftKey && (e.key === "<" || e.key === "Б")) {
        // Decrease speed
        video.playbackRate = Math.max(video.playbackRate - 0.25, 0.25); // Minimum 0.25x
        keyHandled = true;
      } else if (e.key === "j" || e.key === "J" || e.key === "о" || e.key === "О") {
        video.currentTime = Math.max(video.currentTime - 10, 0);
        keyHandled = true;
      } else if (e.key === "k" || e.key === "K" || e.key === "л" || e.key === "Л") {
        if (video.paused) {
          video.play().catch((err) => console.error("Play failed:", err)); // Add error handling for play()
        } else {
          video.pause();
        }
        keyHandled = true;
      } else if (e.key === "l" || e.key === "L" || e.key === "д" || e.key === "Д") {
        if (video.duration && isFinite(video.duration)) {
          video.currentTime = Math.min(video.currentTime + 10, video.duration);
        }
        keyHandled = true;
      }
      if (keyHandled) {
        e.preventDefault();
      }
    });
  }
})();
