// ==UserScript==
// @name         YouTube Toggle Translation Subtitles for French, German, Russian, Ukrainian
// @namespace    http://tampermonkey.net/
// @version      1.0
// @license      Unlicense
// @description  Add dual subtitles to YouTube videos
// @author       Jim Chen
// @homepage     https://jimchen.me
// @match        https://www.youtube.com/*
// @match        https://m.youtube.com/*
// @match        https://cdn.jimchen.me/*
// @run-at       document-idle
// ==/UserScript==
(function () {
  "use strict";

  console.log("[Dual Subs] Script initialized");

  let processingSubtitles = false;
  async function handleVideoNavigation() {
    console.log("[Dual Subs] Navigation detected");

    let videoID = extractYouTubeVideoID();
    if (videoID == null) return;

    console.log(`[Dual Subs] videoID ${videoID}`);

    if (processingSubtitles) {
      console.log(`[Dual Subs] Processed Subtitles, Returning`);
      return;
    }
    processingSubtitles = true;
    await processSubtitles();
    processingSubtitles = false;
  }

  function extractYouTubeVideoID() {
    const url = window.location.href;

    const patterns = {
      standard: /(?:https?:\/\/)?(?:www\.)?youtube\.com\/watch\?v=([^&]+)/,
      embed: /(?:https?:\/\/)?(?:www\.)?youtube\.com\/embed\/([^?]+)/,
      mobile: /(?:https?:\/\/)?(?:www\.)?youtu\.be\/([^?]+)/,
    };

    let videoID = null;

    if (patterns.standard.test(url)) {
      videoID = url.match(patterns.standard)[1];
    } else if (patterns.embed.test(url)) {
      videoID = url.match(patterns.embed)[1];
    } else if (patterns.mobile.test(url)) {
      videoID = url.match(patterns.mobile)[1];
    }

    return videoID;
  }

  async function processSubtitles() {
    console.log("[Dual Subs] Starting subtitle processing");

    const playerData = await new Promise((resolve) => {
      const checkForPlayer = () => {
        console.log("[Dual Subs] Trying to get Caption Data");

        let ytAppData = document.querySelector("#movie_player");
        let captionData = ytAppData?.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.captionTracks;

        if (captionData) {
          const fetchedBaseUrl = captionData[0].baseUrl;
          const fetchedVideoID = fetchedBaseUrl.match(/[?&]v=([^&]+)/)?.[1];

          let videoID = extractYouTubeVideoID();

          console.log(`[Dual Subs] fetchedVideoID ${fetchedVideoID}`);

          if (fetchedVideoID !== videoID) {
            console.log(`[Dual Subs] fetchedVideoID !== videoID`);
            setTimeout(checkForPlayer, 1000);
          } else {
            console.log("[Dual Subs] Successfully retrieved caption data");
            resolve(captionData);
          }
        } else {
          console.log("[Dual Subs] Caption data not found, retrying");
          setTimeout(checkForPlayer, 1000);
        }
      };
      checkForPlayer();
    });

    if (!playerData) {
      console.log("[Dual Subs] No player data available");
      return;
    }

    await addSubtitles(playerData);
  }

  async function addSubtitles(playerData) {
    console.log("[Dual Subs] Finding auto-generated track");

    const hasForeignTrack = playerData.some(({ vssId }) => /(ru|uk|de|fr)/.test(vssId));

    if (hasForeignTrack) {
      const autoGeneratedTrack = playerData.find((track) => ["a.ru", "a.uk", "a.de", "a.fr"].includes(track.vssId));
      const manualTrack = playerData.find((track) => ["ru", "uk", "de", "fr"].some((code) => track.vssId.includes(code)));
      const otherTrack = autoGeneratedTrack || manualTrack;
      if (!otherTrack) {
        console.log("[Dual Subs] I am not learning the language of the video");
        return;
      }
      await addOneSubtitle(`${otherTrack.baseUrl}&fmt=vtt`);
    }
  }

  async function addOneSubtitle(url, maxRetries = 5, delay = 1000) {
    // 1. Parse VTT
    // 2. Create HTML Element
    // 3. Display highlight of subtitle
    // 4. Display Subtitle

    let currentVideo = null;

    currentVideo = document.querySelector("video");
    if (!currentVideo) return;

    try {
      // Step 1

      const response = await fetch(url);
      const subtitleData = await response.text();

      function parseVTTTime(timeStr) {
        const parts = timeStr.split(/[:,\.]/);
        return +parts[0] * 3600 + +parts[1] * 60 + +parts[2] + +parts[3] / 1000;
      }

      function parseVTT(subtitleData) {
        subtitleQueue = [];
        const lines = subtitleData.split("\n");
        let i = 0;

        // Skip the WEBVTT header and any comments/styles
        while (i < lines.length && !lines[i].includes("-->") && lines[i].trim() !== "") {
          i++;
        }

        while (i < lines.length) {
          if (lines[i].trim() === "") {
            i++;
            continue;
          }
          if (lines[i].includes("-->")) {
            // Handle timestamp line
            const timeMatch = lines[i].match(/(\d+:\d+:\d+\.\d+)\s+-->\s+(\d+:\d+:\d+\.\d+)/);
            if (timeMatch) {
              const [_, start, end] = timeMatch;
              let text = "";
              i++;

              // Collect all text lines until an empty line
              while (i < lines.length && lines[i].trim() !== "") {
                text += (text ? " " : "") + lines[i].trim();
                i++;
              }

              subtitleQueue.push({
                start: parseVTTTime(start),
                end: parseVTTTime(end),
                text: text,
              });
            } else {
              i++;
            }
          } else {
            // Skip identifiers or other non-timing lines
            i++;
          }
        }
        return subtitleQueue;
      }

      // Step 2

      let subtitleDiv = null;
      let subtitleQueue = [];

      subtitleQueue = parseVTT(subtitleData);

      function createSubtitleDiv() {
        // Find the video container and get its dimensions
        const videoRect = currentVideo.getBoundingClientRect();

        // Create subtitle div
        subtitleDiv = document.createElement("div");
        subtitleDiv.id = "video-subitles";
        subtitleDiv.style.position = "absolute";
        subtitleDiv.style.background = "rgba(0,0,0,0.7)";
        subtitleDiv.style.color = "white";
        subtitleDiv.style.fontSize = "30px";
        subtitleDiv.style.padding = "5px";
        subtitleDiv.style.zIndex = "9999";
        subtitleDiv.style.width = "fit-content";
        subtitleDiv.style.maxWidth = "80%";
        subtitleDiv.style.textAlign = "center";

        // Initial position: centered at the bottom of the video
        const initialX = videoRect.left + videoRect.width / 2;
        const initialY = videoRect.bottom - 50; // 50px from bottom of video

        subtitleDiv.style.left = initialX + "px";
        subtitleDiv.style.top = initialY + "px";
        subtitleDiv.style.transform = "translateX(-50%)"; // Center horizontally

        // Add the subtitle div to the body
        document.body.appendChild(subtitleDiv);
      }

      createSubtitleDiv();

      function createSubtitleElement(text) {
        const element = document.createElement("div");
        element.textContent = text;
        return element;
      }

      function displaySubtitle(index) {
        if (index >= 0 && index < subtitleQueue.length) {
          const subtitle = subtitleQueue[index];
          return createSubtitleElement(subtitle.text);
        }
        return null;
      }

      currentVideo.ontimeupdate = () => {
        const currentTime = currentVideo.currentTime;
        const currentIndex = subtitleQueue.findIndex((sub) => currentTime >= sub.start && currentTime <= sub.end);

        // Clear the subtitle div first
        while (subtitleDiv.firstChild) {
          subtitleDiv.removeChild(subtitleDiv.firstChild);
        }

        if (currentIndex !== -1) {
          subtitleDiv.appendChild(displaySubtitle(currentIndex));
          if (currentIndex < subtitleQueue.length - 1) {
            subtitleDiv.appendChild(displaySubtitle(currentIndex + 1));
          }
        }
      };

      console.log(`[Dual Subs] Successfully added subtitle display. Found ${subtitleQueue.length} subtitles.`);
    } catch (error) {
      console.error("[Dual Subs] Error:", error);
      if (maxRetries > 0) {
        console.log(`[Dual Subs] Retrying... (${maxRetries} attempts remaining)`);
        await new Promise((resolve) => setTimeout(resolve, delay));
        return addOneSubtitle(url, maxRetries - 1, delay);
      }
    }
  }

  let lastUrl = location.href;
  const observer = new MutationObserver(() => {
    if (location.href !== lastUrl) {
      lastUrl = location.href;
      handleVideoNavigation();
    }
  });

  observer.observe(document.body, { childList: true, subtree: true });

  handleVideoNavigation();
})();













// <div class="caption-window ytp-caption-window-bottom" id="caption-window-_52" dir="ltr" tabindex="0" draggable="true" style="touch-action: none; background-color: rgba(8, 8, 8, 0.25); text-align: center; left: 50%; width: 511px; margin-left: -255.5px; bottom: 2%;">
//   <span class="captions-text" style="overflow-wrap: normal; display: block;">
//     <span class="caption-visual-line" style="display: block;">
//       <span class="ytp-caption-segment" style="display: inline-block; white-space: pre-wrap; background: rgba(8, 8, 8, 0.75); font-size: 25.475px; color: rgb(255, 255, 255); fill: rgb(255, 255, 255);">если он отключит Starlink, мы с вами&nbsp;</span>
//     </span>
//   </span>
// </div>
