// ==UserScript==
// @name         YouTube Toggle Translation Subtitles for French, German, Russian, Ukrainian
// @namespace    http://tampermonkey.net/
// @version      1.0
// @license      Unlicense
// @description  Add dual subtitles to YouTube videos
// @author       Jim Chen
// @homepage     https://jimchen.me
// @match        https://www.youtube.com/*
// @match        https://m.youtube.com/*
// @match        https://cdn.jimchen.me/*
// @run-at       document-idle
// ==/UserScript==
(function () {
  "use strict";

  console.log("[Dual Subs] Script initialized");

  let processingSubtitles = false;
  let subtitleDiv = null;
  let subtitleQueue = [];
  let currentVideo = null;

  async function handleVideoNavigation() {
    console.log("[Dual Subs] Navigation detected");

    let videoID = extractYouTubeVideoID();
    if (videoID == null) return;

    console.log(`[Dual Subs] videoID ${videoID}`);

    if (processingSubtitles) {
      console.log(`[Dual Subs] Processed Subtitles, Returning`);
      return;
    }
    processingSubtitles = true;
    removeSubs();
    await processSubtitles();
    processingSubtitles = false;
  }

  function extractYouTubeVideoID() {
    const url = window.location.href;

    const patterns = {
      standard: /(?:https?:\/\/)?(?:www\.)?youtube\.com\/watch\?v=([^&]+)/,
      embed: /(?:https?:\/\/)?(?:www\.)?youtube\.com\/embed\/([^?]+)/,
      mobile: /(?:https?:\/\/)?(?:www\.)?youtu\.be\/([^?]+)/,
    };

    let videoID = null;

    if (patterns.standard.test(url)) {
      videoID = url.match(patterns.standard)[1];
    } else if (patterns.embed.test(url)) {
      videoID = url.match(patterns.embed)[1];
    } else if (patterns.mobile.test(url)) {
      videoID = url.match(patterns.mobile)[1];
    }

    return videoID;
  }

  async function processSubtitles() {
    console.log("[Dual Subs] Starting subtitle processing");

    const playerData = await new Promise((resolve) => {
      const checkForPlayer = () => {
        console.log("[Dual Subs] Trying to get Caption Data");

        let ytAppData = document.querySelector("#movie_player");
        let captionData = ytAppData?.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.captionTracks;

        if (captionData) {
          const fetchedBaseUrl = captionData[0].baseUrl;
          const fetchedVideoID = fetchedBaseUrl.match(/[?&]v=([^&]+)/)?.[1];

          let videoID = extractYouTubeVideoID();

          console.log(`[Dual Subs] fetchedVideoID ${fetchedVideoID}`);

          if (fetchedVideoID !== videoID) {
            console.log(`[Dual Subs] fetchedVideoID !== videoID`);
            setTimeout(checkForPlayer, 1000);
          } else {
            console.log("[Dual Subs] Successfully retrieved caption data");
            resolve(captionData);
          }
        } else {
          console.log("[Dual Subs] Caption data not found, retrying");
          setTimeout(checkForPlayer, 1000);
        }
      };
      checkForPlayer();
    });

    if (!playerData) {
      console.log("[Dual Subs] No player data available");
      return;
    }

    await addSubtitles(playerData);
  }

  async function addSubtitles(playerData) {
    console.log("[Dual Subs] Finding auto-generated track");

    const hasForeignTrack = playerData.some(({ vssId }) => /(ru|uk|de|fr)/.test(vssId));

    if (hasForeignTrack) {
      const autoGeneratedTrack = playerData.find((track) => ["a.ru", "a.uk", "a.de", "a.fr"].includes(track.vssId));
      const manualTrack = playerData.find((track) => ["ru", "uk", "de", "fr"].some((code) => track.vssId.includes(code)));
      const otherTrack = autoGeneratedTrack || manualTrack;
      if (!otherTrack) {
        console.log("[Dual Subs] I am not learning the language of the video");
        return;
      }
      await addOneSubtitle(`${otherTrack.baseUrl}&fmt=vtt`);
    }
  }

  function parseVTTTime(timeStr) {
    const parts = timeStr.split(/[:.]/);
    return (+parts[0] * 3600 + +parts[1] * 60 + +parts[2]) + (parts[3] ? +parts[3] / 1000 : 0);
  }

  async function addOneSubtitle(url, maxRetries = 5, delay = 1000) {
    currentVideo = document.querySelector("video");
    if (!currentVideo) return;

    try {
      const response = await fetch(url);
      const subtitleData = (await response.text()).replaceAll("align:start position:0%", "");

      // Create draggable subtitle div
      subtitleDiv = document.createElement("div");
      subtitleDiv.style.position = "absolute";
      subtitleDiv.style.background = "rgba(0,0,0,0.7)";
      subtitleDiv.style.color = "white";
      subtitleDiv.style.fontSize = "30px";
      subtitleDiv.style.padding = "5px";
      subtitleDiv.style.zIndex = "9999";
      subtitleDiv.style.bottom = "10%";
      subtitleDiv.style.left = "50%";
      subtitleDiv.style.transform = "translateX(-50%)";
      subtitleDiv.draggable = true;

      subtitleDiv.ondragstart = (e) => e.dataTransfer.setData('text/plain', null);
      subtitleDiv.ondragend = (e) => {
        subtitleDiv.style.left = e.pageX + 'px';
        subtitleDiv.style.bottom = (window.innerHeight - e.pageY) + 'px';
        subtitleDiv.style.transform = "none";
      };

      document.body.appendChild(subtitleDiv);

      // Parse VTT and create subtitle queue
      subtitleQueue = [];
      const lines = subtitleData.split('\n');
      let currentEntry = null;

      for (let line of lines) {
        if (line.includes('-->')) {
          const [start, end] = line.split(' --> ');
          currentEntry = {
            start: parseVTTTime(start),
            end: parseVTTTime(end),
            text: ''
          };
        } else if (line.trim() && currentEntry && !line.startsWith('WEBVTT')) {
          currentEntry.text = line.trim();
          subtitleQueue.push(currentEntry);
          currentEntry = null;
        }
      }

      // Sync subtitles with video
      currentVideo.ontimeupdate = () => {
        const currentTime = currentVideo.currentTime;
        const activeSub = subtitleQueue.find(sub =>
          currentTime >= sub.start && currentTime <= sub.end
        );
        subtitleDiv.textContent = activeSub ? activeSub.text : '';
      };

      console.log(`[Dual Subs] Successfully added subtitle display`);
    } catch (error) {
      if (maxRetries > 0) {
        console.log(`[Dual Subs] Retrying... (${maxRetries} attempts remaining)`);
        await new Promise((resolve) => setTimeout(resolve, delay));
        return addOneSubtitle(url, maxRetries - 1, delay);
      }
    }
  }

  function removeSubs() {
    console.log("[Dual Subs] Attempting to remove subtitles");
    const video = document.getElementsByTagName("video")[0];
    if (!video) return;
    const tracks = video.getElementsByTagName("track");
    Array.from(tracks).forEach(function (ele) {
      ele.track.mode = "hidden";
      ele.parentNode.removeChild(ele);
    });
    if (subtitleDiv) {
      subtitleDiv.remove();
      subtitleDiv = null;
    }
    if (currentVideo) {
      currentVideo.ontimeupdate = null;
    }
    subtitleQueue = [];
    console.log(`[Dual Subs] Successfully removed subtitles`);
  }

  let lastUrl = location.href;
  const observer = new MutationObserver(() => {
    if (location.href !== lastUrl) {
      lastUrl = location.href;
      handleVideoNavigation();
    }
  });

  observer.observe(document.body, { childList: true, subtree: true });

  handleVideoNavigation();
})();